title: 30DaysUAD
description: "Evaluating UAD algorithms on public datasets and real industry data."

# Use an official GitHub Pages theme via remote_theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional basic settings
markdown: kramdown
permalink: pretty 